# Generated by Django 4.0 on 2022-02-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_ticket_date2_alter_ticket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
