# Generated by Django 4.0 on 2022-02-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='csrfmiddlewaretoken',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
