# Generated by Django 4.0 on 2022-02-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_ticket_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_response',
            name='status',
            field=models.CharField(default='To do', max_length=50),
        ),
    ]
